# Transformer Operations

This notbook follow the Transformer Ops lecture by Mohsena (AI by Hand) [Link](https://www.byhand.ai/p/library-videos-counting-ai-by-hand-transformer-ops).

It covers the foundational layer of operational cost of the transformer architecture. I recommend the availabe Excel worksheets, this implementation is on python.

In [21]:
# Dependencies
import numpy as np
import pandas as pd
import torch
import math

np.random.seed(seed=123)

### What are FLOPs?

Floating Poing Operation (FLOP)

Plural -> FLOPs

Measure per seconds -> FLOPS

### Why do FLOP Matters

Under the hood, Neural Networks (NN) are Matrix operations. SOTA models perform billions of these operations, with Matrix Multiplication dominating FLOPs.

In [2]:
# Random integer
a = np. random.randint(11) # Half-open interval [)
b = np.random.randint(11)

print(f"Random integer a: {a}")
print(f"Random integer b: {b}")

Random integer a: 2
Random integer b: 2


In [3]:
print("Summation corresponds to 1 FLOP")
print(f"Sum of a and b: {a + b}.")
print("Multiplication corresponds to 1 FLOP")
print(f"Product of a and b: {a * b}")


Summation corresponds to 1 FLOP
Sum of a and b: 4.
Multiplication corresponds to 1 FLOP
Product of a and b: 4


In [4]:
# Random vector
vec_a = np.random.randint(11, size=(1,3))
vec_b = np.random.randint(11, size=(1,3))

print(f"Random vector vec_a: {vec_a}, dimension d={vec_a.shape[1]}")
print(f"Random vector vec_b: {vec_b}, dimension d={vec_b.shape[1]}")

Random vector vec_a: [[6 1 3]], dimension d=3
Random vector vec_b: [[10  9  6]], dimension d=3


In [5]:
print("Vector summention corresponds to d FLOPs")
print(f"Sum of vec_a and vec_b: {(vec_a + vec_b)[0]}. Therefore, {vec_a.size} FLOPs")
print("Vector multiplication corresponds to 2d-1 FLOPs")
print(f"Multiplication of vec_a and vec_b: {(vec_a@vec_b.T)[0][0]}. Therefore, {vec_a.size + (vec_a.size-1)} FLOPs")

Vector summention corresponds to d FLOPs
Sum of vec_a and vec_b: [16 10  9]. Therefore, 3 FLOPs
Vector multiplication corresponds to 2d-1 FLOPs
Multiplication of vec_a and vec_b: 87. Therefore, 5 FLOPs


In [6]:
# Random Matrix
mat_a = np.random.randint(11, size=(2,3))

print("Random Matrix mat_a:")
print(mat_a)
print(f"Rows: r={mat_a.shape[0]}, columns: c={mat_a.shape[1]}")

Random Matrix mat_a:
[[1 0 1]
 [9 0 0]]
Rows: r=2, columns: c=3


In [7]:
print("Matrix-vector multiplication correspond to r*(2c-1) FLOPs")
print(f"Multiplication of mat_a {mat_a.shape} and vec_a.T {vec_a.T.shape}:")
print(mat_a@vec_a.T)
print(f"With shape: {(mat_a@vec_a.T).shape}")
print(f"Therefore, {(mat_a.shape[0]*(2*mat_a.shape[1]-1))} FLOPs")

Matrix-vector multiplication correspond to r*(2c-1) FLOPs
Multiplication of mat_a (2, 3) and vec_a.T (3, 1):
[[ 9]
 [54]]
With shape: (2, 1)
Therefore, 10 FLOPs


In [8]:
mat_b = np.random.randint(11, size=(3,4))

print("Random Matrix mat_b:")
print(mat_b)
print(f"Rows: r={mat_b.shape[0]}, columns: c={mat_b.shape[1]}")

Random Matrix mat_b:
[[9 3 4 0]
 [0 4 1 7]
 [3 2 4 7]]
Rows: r=3, columns: c=4


In [9]:
print("Matrix-Matrix multiplication correspond to r1*(c2*(2*c1-1))) FLOPs")
print(f"Multiplication of mat_a {mat_a.shape} and mat_b {mat_b.shape}:")
print(mat_a@mat_b)
print(f"With shape: {(mat_a@mat_b).shape}")
print(f"Therefore, {(mat_a.shape[0]*(mat_b.shape[1]*(2*mat_a.shape[1]-1)))} FLOPs")

Matrix-Matrix multiplication correspond to r1*(c2*(2*c1-1))) FLOPs
Multiplication of mat_a (2, 3) and mat_b (3, 4):
[[12  5  8  7]
 [81 27 36  0]]
With shape: (2, 4)
Therefore, 40 FLOPs


It is clear that FLOPs rapidly increase with larger matrices

In [10]:
mat_c = np.random.randint(11, size=(12,10))
mat_d = np.random.randint(11, size=(10,20))

print(f"Random Matrix mat_c shape: {mat_c.shape}")
print(f"Random Matrix mat_d shape: {mat_d.shape}")

mat_e = mat_c@mat_d

print(f"Matrix mat_e = mat_c@mat_d, with shape: {mat_e.shape}")
print(f"FLOPs = {mat_c.shape[0]*(mat_d.shape[1]*(mat_c.shape[1]+(mat_c.shape[1]-1)))}")

Random Matrix mat_c shape: (12, 10)
Random Matrix mat_d shape: (10, 20)
Matrix mat_e = mat_c@mat_d, with shape: (12, 20)
FLOPs = 4560


## Flow of the Transformer Architecture

Overview

Input token embeddings -> Attention -> Feed Forward Network (FNN) -> Output

Input -> Q,K,V projections -> Attention Matrix -> Output projection -> FFN -> Output

Total FLOPs = Attention FLOPs + FFN FLOPs

### IMPORTANT PARAMETERS

1. Sequence length (n): tokens processed at once.
2. Embedding Size (d): Size of the vector representation of each token. Larger d provides a richer representation of the token, but increases the computation O(d^2).
3. Number of heads (h): Instead of one large attention system, we split attention into multiple heads 
4. Head dimension (d_k): dimension of projection matrices. Reminder: d_k = d/h.
5. Number of layers (L): Repeated processing block

Each layer contains -> Attention + FNN

Transformer FLOPs = L x Layer FLOPs

In [11]:
def matmul_flops_count(mat1_shape, mat2_shape):
    r1, c1 = mat1_shape
    r2, c2 = mat2_shape

    if c1 != r2:
        raise ValueError("Matrix dimensions are not compatible for multiplication.")
    else:
        return r1 * (c2 * (2 * c1 - 1))

In [12]:
n = 6
d = 9
h = 3
d_k = int(d/h) # dimension Q, K, and V. 
L = 3

# Input
x = torch.rand(n,d)
# x = np.random.randint(4, size=(d,n))
print(f"Input shape: {x.shape}")
print(x)


Input shape: torch.Size([6, 9])
tensor([[0.5426, 0.3829, 0.0208, 0.7340, 0.6196, 0.0519, 0.3180, 0.5823, 0.4673],
        [0.7290, 0.2096, 0.6885, 0.8200, 0.6236, 0.1628, 0.0459, 0.4922, 0.1968],
        [0.3844, 0.3879, 0.3964, 0.2069, 0.7042, 0.9587, 0.8489, 0.9482, 0.9749],
        [0.0810, 0.7485, 0.5127, 0.1489, 0.9282, 0.0434, 0.5654, 0.6806, 0.2149],
        [0.3292, 0.5036, 0.2625, 0.4719, 0.6047, 0.5872, 0.1828, 0.0119, 0.1656],
        [0.9679, 0.6025, 0.4744, 0.7803, 0.9448, 0.0972, 0.7349, 0.4878, 0.0245]])


## Attention BLOCK

Attention requires 3 projection Matrices: W_q, W_k, and W_v

Q = x@W_q

K = x@W_k

V = x@W_v

In [13]:
W_q = torch.rand(d,d_k)
W_k = torch.rand(d,d_k)
W_v = torch.rand(d,d_k)

print(f"Projection Matrices shape: {W_q.shape}")

Projection Matrices shape: torch.Size([9, 3])


In [14]:
Q = x@W_q
K = x@W_k
V = x@W_v

proj_flops = matmul_flops_count(x.shape, W_q.shape)
att_proj_flops = 3 * proj_flops
mha_proj_flops = h * att_proj_flops

print(f"Attention Matrices (Q,K,V) shape: {Q.shape}")
print(f"Single projection FLOPs = {proj_flops}")
print(f"Total Projections FLOPs = 3 * Projection FLOPs: {att_proj_flops}")
print(f"MHA projections FLOPs = h * total projection FLOPs : {mha_proj_flops}")

Attention Matrices (Q,K,V) shape: torch.Size([6, 3])
Single projection FLOPs = 306
Total Projections FLOPs = 3 * Projection FLOPs: 918
MHA projections FLOPs = h * total projection FLOPs : 2754


### Attention Computation FLOPs

Attention output computation requires 3 steps:

1. Compute the attention matrix: A = Q@K^T/sqrt(dq).

Note: Transpose does not require FLOPs.

2. Apply softmax to the attention matrix: A' = softmax(A)

softmax = exp(A)/sum(exp(A))

3. Compute the output: O = A'@V

4. Concatenate the output of all heads and apply the output projection: O' = O@W_o



In [24]:
A = (Q@K.T)/math.sqrt(d_k)

att_mat_mul_flops = matmul_flops_count(Q.shape, K.T.shape)
div_flops = A.numel() # Ignore single FLOP from sqrt.
att_flops = att_mat_mul_flops + div_flops
mha_att_flops = h * att_flops

print(f"Attention Matrix A shape: {A.shape}")
print(f"Attention FLOPs = matrix multiplication + matrix division: {att_mat_mul_flops} + {div_flops} = {att_flops}")
print(f"MHA Attention Matrices FLOPs = h * Attention FLOPs: {mha_att_flops}")



Attention Matrix A shape: torch.Size([6, 6])
Attention FLOPs = matrix multiplication + matrix division: 180 + 36 = 216
MHA Attention Matrices FLOPs = h * Attention FLOPs: 648


Consider Attention Matrix A with shape (n,n) = (6,6).

For a single row, softmat requires n exponentials, n-1 additions, and n divisions.

Considering n rows, Total FLOPs = n^2 exponentials + n^2-n additions + n^2 divisions = 3n^2 - n

In [16]:
softmax = torch.nn.Softmax(1)
sm_A = softmax(A)

softmax_flops = 3 * A.numel() - A.shape[0] # 3n^2 - n
mha_softmax_flops = h * softmax_flops

print(f"Softmax FLOPs = 3n^2 - n: {softmax_flops}")
print(f"MHA Softmax FLOPs = h * softmax_flops: {mha_softmax_flops}")

Softmax FLOPs = 3n^2 - n: 102
MHA Softmax FLOPs = h * softmax_flops: 306


In [17]:
att_output = sm_A@V

att_output_flops = matmul_flops_count(sm_A.shape, V.shape)
mha_output_flops = h * att_output_flops

print(f"sm_A shape: {sm_A.shape}, V shape: {V.shape}")
print(f"Output shape: {att_output.shape}")
print(f"Output FLOPs = {att_output_flops}")
print(f"MHA Output FLOPs = h * output FLOPs: {mha_output_flops}")

sm_A shape: torch.Size([6, 6]), V shape: torch.Size([6, 3])
Output shape: torch.Size([6, 3])
Output FLOPs = 198
MHA Output FLOPs = h * output FLOPs: 594


Concatenation of the output of all heads and apply the output projection: O' = O@W_o

O = concatenate([O_1, O_2, ..., O_h], axis=-1)

O' = O@W_o

NOTE: Concatenation does not require FLOPs, but the output projection does.

In [18]:
print(f"Attention heads: {h}")

# To facilitate, we will copy the one output generated for the other attention heads.
att_output1 = att_output.clone()
att_output2 = att_output.clone()
att_output3 = att_output.clone()

concat_output = torch.cat((att_output1, att_output2, att_output3), dim=1)
print(f"Concatenated output shape: {concat_output.shape}")

Attention heads: 3
Concatenated output shape: torch.Size([6, 9])


In [19]:
W_o = torch.rand(d,d)

proj_output = concat_output@W_o
proj_output_flops = matmul_flops_count(concat_output.shape, W_o.shape)

print(f"Output projection shape: {proj_output.shape}")
print(f"Output projection FLOPs = {proj_output_flops}")

Output projection shape: torch.Size([6, 9])
Output projection FLOPs = 918


In [23]:
# Create table with all FLOPs

FLOPs_data = {
    "Operation": [
        "QKV Projections",
        "MHA Attention Matrices",
        "MHA Softmax",
        "MHA Output",
        "Output Projection",
        "Total FLOPs"
    ],
    "FLOPs": [
        mha_proj_flops,
        mha_att_flops,
        mha_softmax_flops,
        mha_output_flops,
        proj_output_flops,
        mha_proj_flops + mha_att_flops + mha_softmax_flops + mha_output_flops + proj_output_flops
    ]
}

Table_FLOPs = pd.DataFrame(FLOPs_data)
Table_FLOPs

,Operation,FLOPs
0,QKV Projections,2754
1,MHA Attention Matrices,648
2,MHA Softmax,306
3,MHA Output,594
4,Output Projection,918
5,Total FLOPs,5220
